pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                       apt install -y --force-yes python3-pip
                       pip3 install numpy && pip3 install matplotlib
                       cd ./tracking
                       python3 -m unittest
                   ''' 
               }
             }
          }
        }
}
