pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                       cd ./tracking
                       ls
                       python -m unittest
                   ''' 
               }
             }
          }
        }
}
