pipeline {
    agent {
       label "deploy"
    }
    stages {
          stage("connect") {
             steps {
               script {
                   sh '''
                   make image VERSION=jetson_site2 FILE=./jetson_site/Dockerfile BRANCH=null
                   make push VERSION=jetson_site2
                   '''
               }
             }
          }
        }
} 
